name: Publish to PyPI

on:
  push:
    tags:
      - "v0.1.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: uv pip install -e ".[dev]"

    - name: Run tests
      run: uv run pytest tests/ -v
      env:
        LUMNISAI_DISABLE_TELEMETRY: "1"

    - name: Build package
      run: uv build

    # Temporarily disabled TestPyPI steps to focus on PyPI publishing
    # - name: Publish to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     repository-url: https://test.pypi.org/legacy/
    #     skip-existing: true

    # - name: Wait for TestPyPI
    #   run: sleep 30

    # - name: Test install from TestPyPI
    #   run: |
    #     uv pip install --index-url https://test.pypi.org/simple/ \
    #       --extra-index-url https://pypi.org/simple/ \
    #       lumnisai==${{ github.ref_name }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}